# Generated by cpp11: do not edit by hand

convert_log2_scale_inverse_cpp <- function(dt, vars_to_transform, smallest_value) {
  .Call(`_epikinetics_convert_log2_scale_inverse_cpp`, dt, vars_to_transform, smallest_value)
}

simulate_trajectories_cpp <- function(person_params) {
  .Call(`_epikinetics_simulate_trajectories_cpp`, person_params)
}
